on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
      - run: docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j -t https://demo.website.net -r testreport.html --hook=/zap/auth_hook.py -z "auth.loginurl=https://demo.website.net/login/index.php auth.username="admin" auth.password="sandbox""
